/** Verify message editing through the native IDEA bridge in an isolated fixture profile. */
import { connectNative } from './native-bridge.mjs';
import { mkdirSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';

const output = 'output/playwright';
mkdirSync(output, { recursive: true });
const runId = Date.now();
const { native, findChat, close } = await connectNative();
async function submitEdit(page, itemId, replacement) {
  const message = page.locator(`article[data-message-id="${itemId}"]`);
  await message.hover();
  await message.getByRole('button', { name: 'Edit message', exact: true }).click();
  await message.getByRole('textbox', { name: 'Edit message text', exact: true }).fill(replacement);
  await message.getByRole('button', { name: 'Edit and resend', exact: true }).click();
}
try {
  const existing = await findChat(() => true);
  await native(existing.page, 'openThread', { id: 'review' });
  const { page, chat: source } = await findChat(chat => chat.threadId === 'review');
  await native(page, 'openThread', { id: source.id });
  writeFileSync(`${output}/edit-accessibility.txt`, await page.locator('body').ariaSnapshot());
  assert.ok(await page.getByRole('button', { name: 'Edit message', exact: true }).count(), 'Every user message needs an Edit action');
  assert.equal(await page.getByRole('button', { name: 'Edit message', exact: true }).count(), source.items.filter(item => item.type === 'userMessage').length);
  assert.equal(await page.locator('article[data-message-role="assistant"]').getByRole('button', { name: 'Edit message', exact: true }).count(), 0);
  const message = page.locator('article[data-message-id="review-edit"]');
  await message.scrollIntoViewIfNeeded();
  await page.mouse.move(0, 0);
  const before = await message.boundingBox();
  const edit = message.getByRole('button', { name: 'Edit message', exact: true });
  const appearance = () => edit.evaluate(element => ({ color: getComputedStyle(element).backgroundColor, filter: getComputedStyle(element).filter }));
  const idle = await appearance();
  await message.hover();
  await edit.hover();
  assert.equal((await message.boundingBox()).height, before.height, 'Hover does not expand the message');
  const hover = await appearance();
  await page.mouse.down();
  const pressed = await appearance();
  await page.mouse.up();
  assert.notDeepEqual(idle, hover);
  assert.notDeepEqual(hover, pressed);
  const field = message.getByRole('textbox', { name: 'Edit message text', exact: true });
  await field.waitFor();
  assert.equal(await field.inputValue(), 'Please focus on tab restoration.');
  await field.fill('Canceled edit');
  await field.press('Escape');
  assert.equal(await field.count(), 0, 'Escape cancels the edit');
  await page.waitForFunction(() => document.activeElement?.getAttribute('aria-label') === 'Edit message', null, { timeout: 3000 });
  assert.ok(await edit.evaluate(element => element === document.activeElement), 'Cancel returns keyboard focus');
  await page.getByRole('textbox', { name: 'Message Codex', exact: true }).fill('Unsent draft in the original chat');
  await native(page, 'draft', { text: 'Unsent draft in the original chat', attachments: [] });
  await submitEdit(page, 'review-edit', `REVISED_RESTORATION_REQUEST_${runId}`);
  const revised = await findChat(chat => chat.id !== source.id && JSON.stringify(chat.items).includes(`REVISED_RESTORATION_REQUEST_${runId}`));
  const encoded = JSON.stringify(revised.chat.items);
  assert.ok(encoded.includes('Each chat has its own editor tab'), 'Earlier assistant context is retained');
  assert.ok(encoded.includes('preview.svg'), 'The image attachment is retained');
  assert.ok(!encoded.includes('Please focus on tab restoration.'), 'Original message is replaced in the branch');
  assert.ok(!encoded.includes('Later instruction must not enter edited history.'), 'Later turns are excluded');
  assert.ok(!encoded.includes('The old toolbar was kept.'), 'Responses to the old message are excluded');
  const unchanged = (await native(page, 'ready')).chat;
  assert.deepEqual(unchanged.items, source.items, 'The original transcript is untouched');
  assert.equal(unchanged.draft, 'Unsent draft in the original chat');
  await revised.page.screenshot({ path: `${output}/message-edit-branch.png` });
  await native(revised.page, 'openThread', { id: source.id });
  await submitEdit(page, 'review-steer', `REVISED_STEERING_REQUEST_${runId}`);
  const steering = await findChat(chat => JSON.stringify(chat.items).includes(`REVISED_STEERING_REQUEST_${runId}`));
  const steeringText = JSON.stringify(steering.chat.items);
  assert.ok(steeringText.includes('Please focus on tab restoration.'), 'Earlier input from the same turn is retained');
  assert.ok(steeringText.includes('preview.svg'), 'Earlier attachment from the same turn is retained');
  assert.ok(!steeringText.includes('Keep the old toolbar.'), 'Old steering text is excluded');
  await native(steering.page, 'openThread', { id: source.id });
  await submitEdit(page, 'review-user', `FIRST_MESSAGE_EDIT_${runId}`);
  const first = await findChat(chat => JSON.stringify(chat.items).includes(`FIRST_MESSAGE_EDIT_${runId}`));
  assert.equal(first.chat.items.filter(item => item.type === 'userMessage').length, 1, 'Editing the first message starts with clean history');
  await native(first.page, 'openThread', { id: source.id });
  await submitEdit(page, 'review-edit', `FIXTURE_RETRY_EDIT_${runId}`);
  const failed = await findChat(chat => chat.error?.includes('Fixture send failed once') && chat.draft?.includes(`FIXTURE_RETRY_EDIT_${runId}`));
  assert.ok(failed.chat.draft.includes(`FIXTURE_RETRY_EDIT_${runId}`));
  assert.equal(failed.chat.draftInput[0].type, 'localImage', 'Failed send retains the attachment for retry');
  await failed.page.getByRole('button', { name: 'Send message', exact: true }).click();
  await failed.page.getByText('Message received in this conversation. The other tabs are unchanged.', { exact: true }).waitFor();
  const retried = (await native(failed.page, 'ready')).chat;
  assert.equal(retried.error, '');
  assert.equal(retried.draft, '');
  assert.ok(JSON.stringify(retried.items).includes('preview.svg'));
  const result = { anyUserMessage: true, cancel: true, stableHover: true, pressed: true, newNativeTab: true, originalPreserved: true, priorHistory: true, attachments: true, steeringEdit: true, firstMessageEdit: true, failedSendRetry: true };
  writeFileSync(`${output}/message-edit-result.json`, JSON.stringify(result, null, 2));
  console.log(result);
} finally { await close(); }
